### ISSUE TITLE
Process runs in VS Code directory

### ISSUE THREAD

**Issue by roncli** [Miramac/vscode-exec-node#1]
The current working directory that node.js runs in matches the working directory that VS Code runs in.  It should instead run in the same directory as the file that it's running.

**Comment by roncli** [comment]
I haven't messed with VS Code extensions before, but glancing over the code, I believe the following changes will make it work as expected:

On line 53 of /lib/activate.js, add a 3rd parameter to the spawn function so it works like so:

`vqProcess = spawn('node', [tmpFile], {cwd: dirName})`

(Also, minor note, you have a pair of typos on line 42 (`Unkown` vs `Unknown`, and `befor` vs `before`).)

**Comment by wangk784** [comment]
Thank u so much for the solution.

**Comment by Miramac** [comment]
I'm sorry, I was in the last 3 weeks on holiday :)

Thanks for your solution and the corrections! I will fix it as soon as possible.
