### ISSUE TITLE
Two latest updates have both broken the extension for me

### ISSUE THREAD

**Issue by mdgriest** [Miramac/vscode-exec-node#11]
Yesterday's update caused the process to get stuck in a "Running" state without ever making progress. There is already an issue for it [here](https://github.com/Miramac/vscode-exec-node/issues/10).

Today's patch fixed the perpetual run, but still does not work. When I press F8 like I have always done to use this extension, I now see the following output:

```
Info: Start process (8:14:27 AM)
Process error: 
Error: spawn node ENOENT
Info: End process with errors (8:14:27 AM)
Info: End process (8:14:27 AM)
```

I am using node 6.4.0 on a Mac running OSX 10.11.6

**Comment by Miramac** [comment]
I just publish an old version of the extension - I hope the bug is fixed until I find the real cause for this issue.

**Comment by mdgriest** [comment]
@Miramac Thank you for taking action so quickly! Things are working again with the older version in place. Good luck finding the issue. Your extension is incredibly useful and I was dying without it.

**Comment by shoyuf** [comment]
If set enviroment variables It will throw this error
I think maybe VSCode don't support spawn with any env

macOS 14.1.1 VSCode 1.85.1
