### ISSUE TITLE
Is this now CLOSED SOURCE?

### ISSUE THREAD

**Issue by rnemec** [Miramac/vscode-exec-node#12]
When I see last few versions not reflected on github AND the marketplace suddenly does not list the repository, I get paranoid.

**Comment by Miramac** [comment]
I published yesterday an old version because of some problems with the current release. In the older version the repo is missing in the package.json. 
The extension is and will be ever open source :)

**Comment by rnemec** [comment]
Thanks for your explanation (paranoia cured), your work contributing to the community and also for the friendly attitude!
