### ISSUE TITLE
No option to show code total execution time, only execution start and end timestamps

### ISSUE THREAD

**Issue by 0x2E757** [Miramac/vscode-exec-node#13]
It would be awesome, if under line with end process timestamp there would be one more line, with code total execution time, especially with milliseconds. It could help to measure code performance a lot. I suggest line with "Info: Execution time hh:mm:ss.fff" formatting.

**Comment by Miramac** [comment]
Yes, I also think that would be a useful information. I'll add it with the next release.

**Comment by Miramac** [comment]
Finally, I found some time to publish the new version.
But you have to turn off the ``legacyMode``. Some people had strange problems because of small changes in the extension, so I added the LegacyMode option which is set by default

Just add this to your settings:
````
{
  "miramac.node.legacyMode": false
}
`````
