### ISSUE TITLE
Nodemon support

### ISSUE THREAD

**Issue by ftuyama** [Miramac/vscode-exec-node#2]
It would be great if the tool had support to run nodemon command (and automatically update the execution).

**Comment by Miramac** [comment]
I like the idea with nodemon. But it's probably only usefull when executing the entire file, not just a selection. I'll check if its possible and how it can be implemented.

**Comment by Miramac** [comment]
Unfortunately there is no good solution for this. Just replacing the two processes won't do the job. Also some functions from nodemon are missing (eg. typing `rs` to manually restart the prozess or colors).
I think using the integrated terminal from vscode is way better.

But if it is important for you to run the current file with nodemon, take a look at this plugin for vscode: https://github.com/formulahendry/vscode-code-runner
It's doing basically the same but seems to be more sophisticated then my project ;)

**Comment by ftuyama** [comment]
Oh, thank you for the tip! I really enjoy your project, great job!
