### ISSUE TITLE
command 'extension.miramac.node.exec' not found

### ISSUE THREAD

**Issue by resting** [Miramac/vscode-exec-node#20]
I get the warning above when I hit F8.
Tried restarting VSC and still getting the same thing.
What does it mean? The extension is installed and enabled.

**Comment by Miramac** [comment]
sorry no clue... 
what happen if you press F1 and then type `Execute Node.js`?

**Comment by resting** [comment]
It shows the same message but with the `Error` label.  
F8 shows the message with `Warn` label.

**Comment by Miramac** [comment]
This is really strange.
Which version of VSCode and Node Exec do you use? And on which system?

**Comment by resting** [comment]
macOS 10.12.4
node v7.10.0
VSC v1.12.1

What about the environment you're using it with?

**Comment by Miramac** [comment]
I have tested it with
node 6.10 and 7.10 
Win 7 and macOS 10.12
VSC v1.12.1

I suspect the add-in files on you system are not present or corrupt.
You can try to delete the extension and reinstall it.

If everything doesn't help, you can look at this extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

I think it is very similar to my extension (and much more ;)

sorry...!

**Comment by resting** [comment]
You were right it was corrupted 😂 
Just reinstalled it and it's working now 👍
