### ISSUE TITLE
F9 is not available as a key and there's no option for custom keybind

### ISSUE THREAD

**Issue by Inventsable** [Miramac/vscode-exec-node#28]
Love this extension but just recently got a new Windows keyboard where F9 opens Cortana and there is no way to override this, even through OS level keymasking via AutoHotKey.

Would really appreciate the ability to change this to a different key in the Preferences menu (as is standard with most other extensions relying on hotkeys due to the potential of keybinding conflicts just like this one) instead of being stuck at F9 because I'm no longer able to use Node Exec because of it 😣

**Comment by Miramac** [comment]
Yeah, I know, it's not very well solved with the shortcuts. The extension needs a total rework...

But you can change the key binding for yourself:
`File -> Preferences -> Keyboard Shortcuts` 
Search for `F9` or `miramac.node.cancel` and set your preferred shortcut.

**Comment by Inventsable** [comment]
Fair enough! Just really like the extension, but this as a short workaround is enough to close the issue I feel. Thanks!
