### ISSUE TITLE
Can't use npm extensions with vscode-exec-node

### ISSUE THREAD

**Issue by theslyprofessor** [Miramac/vscode-exec-node#29]
I have this line of code:
`var wav = require('wav');`

In order to use this code, I have installed the correct module:
`sudo npm -g install wav`

I checked that the extension is visible by my npm using command:
`npm list -g --depth 0`

It indeed shows up as one of the packages, yet vscode-exec-node can't see it for whatever reason. See error below:

```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'wav'
```

Help is greatly appreciated.

Thanks,
Nakul

**Comment by Miramac** [comment]
Sorry for the late response. Maybe you've already figured it out for yourself. 
You have to install npm modules locally and not globally to use them in a program.

Try this in your working directory (without `-g`):
`npm install wav`

Hope this helps!
Miramac
