### ISSUE TITLE
Nao para de rodar e executa o comando

### ISSUE THREAD

**Issue by Emerson-MM-Filho** [Miramac/vscode-exec-node#34]
![Nodejs problema](https://user-images.githubusercontent.com/74127533/103033708-7565f280-4539-11eb-8ac4-35e6c11ffd04.png)

Quando eu aperto F8 para executar o node.js exec, abre o output e informa q o processo iniciou, mas não é mostrado no output o resultado do processo, e ele nao para de rodar, fica rodando infinitamente (Running...)

Estou utilizando o Node.js Exec versão 0.5.3

**Comment by erikgsena** [comment]
![image](https://user-images.githubusercontent.com/64276339/104079670-2390be00-5203-11eb-97ef-d5b7bd20107c.png)

Comigo a extensão nem funciona, fala que o arquivo é inválido. Não sei qual é o problema.

Você poderia passar as configurações json da extensão pra mim ? Só pra poder verificar se tem algo de errado.

**Comment by Emerson-MM-Filho** [comment]
eu nao alterei nenhum config, está tudo nas configurações padrões.

**Comment by ghost** [comment]
Olá, instala o [Node.js](https://nodejs.org/en/)

**Comment by Emerson-MM-Filho** [comment]
ok Jonatas, vou tentar essa solução aqui, obrigado pela dica.
