### ISSUE TITLE
O node.js exec não executa os comandos parece que ele tem um bug

### ISSUE THREAD

**Issue by Moises2005-og** [Miramac/vscode-exec-node#35]

**Comment by ghost** [comment]
Olá. Instala o [Node.js](https://nodejs.org/en/)

**Comment by Moises2005-og** [comment]
Eu tenho ele instalado

**Comment by PiterJackson** [comment]
Tive o mesmo problema e notei que isso ocorreu após a atualização automática do VSCODE, a solução que encontrei foi instalar a versão anterior.

Explico como instalar a versão anterior nesse vídeo -> https://youtu.be/jAi3J3gNp6k.

**Comment by maykbrito** [comment]
Hi everyone! 
Try this! https://youtu.be/0NvJhxhivyk
Hope it helps!

**Comment by Miramac** [comment]
fixed #39
