### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Yuririjo** [Miramac/vscode-exec-node#37]
My VSCODE was updated today and now i'm having this problems to run Node Exec.

> Running the contributed command: 'extension.miramac.node.exec' failed.

> Command 'Execute Node.js' resulted in an error (Running the contributed command: 'extension.miramac.node.exec' failed.)

How can i fix this errors?

**Comment by josericardo-fo** [comment]
Same for me here

**Comment by AaronSSands** [comment]
I'm also getting this error how can I fix

**Comment by Yuririjo** [comment]
I "fix" this error restoring my VSCODE to previous version, but isn't the proper fix. 
Probably is the integration between VSCODE version and Node js exec.

**Comment by Yuririjo** [comment]
@AaronSSands @josericardo-fo 
I "fix" this error restoring my VSCODE to previous version, but isn't the proper fix.
Probably is the integration between the new version of VSCODE and Node js exec.

**Comment by PieVancin** [comment]
Same problem here, first time using this plugin

**Comment by vinifsouza-s** [comment]
@Yuririjo what version of VSCODE did you installed ?

**Comment by AaronSSands** [comment]
its most updated seems to be an issue for everyone I've just started using index.html and running my code in live server better practice anyway

**Comment by PiterJackson** [comment]
I had the same problem and I noticed that this happened after updating the VSCODE, the solution I found was to install the previous version. It sure will do.

I explain how to install the previous version in this video -> https://youtu.be/jAi3J3gNp6k.

**Comment by maykbrito** [comment]
Hi everyone! 
Try this! https://youtu.be/0NvJhxhivyk
Hope it helps!

**Comment by Yuririjo** [comment]
> @Yuririjo what version of VSCODE did you installed ?

I did install version 1.54.3 and now it's working. But, I still don’t know what happened and how it solved 😅

**Comment by Miramac** [comment]
fixed: #39
