### ISSUE TITLE
Running the contributed command: 'extension.miramac.node.exec' failed.

### ISSUE THREAD

**Issue by lucaslopeslima** [Miramac/vscode-exec-node#38]
I can't execute any code, just getting this error, can someone know what's going on and how to fix it?
I have the latest version of Node.js installed.
Already try to instal another version of  vscode-exec-node, and still get the same error..
Sadly.. =/

![errorvscode](https://user-images.githubusercontent.com/63620832/110159213-2d7d0a80-7dc9-11eb-84d1-60f7754fd167.jpg)

**Comment by gillfilho** [comment]
Mesmo problema aqui...

**Comment by FelipeElias021** [comment]
I'm having the same problem, it happened after I ran this code:
'''
var n = 1
while (n <=1000000000000) {
console.log(`Hello ${n}`)
n++
}
'''

**Comment by FelipeElias021** [comment]
I'm having the same problem, it happened after I ran this code:
```
var n = 1
while (n <=1000000000000) {
console.log('Hello ${n}')
n++
} 
```

**Comment by ghost** [comment]
Yeah... me too :(

**Comment by ghost** [comment]
I tried, tried and tried... My only solution was to use Code Runner

**Comment by ghost** [comment]
Que triste, ajudava muito, o que será que aconteceu?

**Comment by groliveira18** [comment]
I just had the same problem after updating vscode. Has anyone managed to solve without returning the version of vscode?

**Comment by T3H1GH** [comment]
Tô com o mesmo problema também

**Comment by juliocbribeiro** [comment]
me too

**Comment by Marikarp** [comment]
mesmo problema

**Comment by PieVancin** [comment]
Same problem here

**Comment by mohitb3** [comment]
Getting the same problem as well

**Comment by Murilo-CS** [comment]
I have the same problem, since Sunday.

**Comment by hpdesenvolvedor** [comment]
Estou com esse problema, desde ontem

**Comment by Gumeyohas** [comment]
mesmo problema aqui, só vi hoje quando fui rodar um código.

**Comment by darshna09** [comment]
I am facing the same problem. It is coming while running a `console.log(0)`.

**Comment by fernandoarmonellifiedler** [comment]
same here. just by running the console. then i unistalled and try to install it again and got

    [error] EPERM: operation not permitted, open

**Comment by maykbrito** [comment]
Hi everyone! Try this! https://youtu.be/0NvJhxhivyk
Hope it helps!

**Comment by PieVancin** [comment]
> Hi everyone! Try this! https://youtu.be/0NvJhxhivyk
> Hope it helps!

Grande Maykão! Deu certo, obrigado!

**Comment by ghost** [comment]
Deu certo aqui também. Muito obrigado.
Grande Abraço!!

**Comment by hpdesenvolvedor** [comment]
Nossa deu certo! Gratidão!!!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb., 13 de mar. de 2021 às 17:25, Mayk Brito ***@***.***>
escreveu:

**Comment by Gumeyohas** [comment]
hi Mayk Brito, i did all those things that you have done in this video and when i was testing it, there was a bug with the term "undefined", im gonna put here:



________________________________
De: Mayk Brito ***@***.***>
Enviado: sábado, 13 de março de 2021 18:25
Para: Miramac/vscode-exec-node ***@***.***>
Cc: Gumeyohas ***@***.***>; Comment ***@***.***>
Assunto: Re: [Miramac/vscode-exec-node] Running the contributed command: 'extension.miramac.node.exec' failed. (#38)


Hi everyone! Try this! https://youtu.be/0NvJhxhivyk
Hope it helps!

**Comment by Gumeyohas** [comment]
hi Mayk Brito, i did all those things that you have done in this video and when i was testing it, there was a bug with the term "undefined", im gonna put here:
![2021-03-14 (2)](https://user-images.githubusercontent.com/79321718/111079247-f3ea8480-84d7-11eb-9853-017ac16207a9.png)

**Comment by maykbrito** [comment]
> hi Mayk Brito, i did all those things that you have done in this video and when i was testing it, there was a bug with the term "undefined", im gonna put here:
> ![2021-03-14 (2)](https://user-images.githubusercontent.com/79321718/111079247-f3ea8480-84d7-11eb-9853-017ac16207a9.png)

Try to uninstall the extension, and do it again. Also, try another shell, like git bash

**Comment by williamrlopes** [comment]
Great @maykbrito! Thanks for this.

**Comment by GarethRoddy** [comment]
Thanks @maykbrito, works well!

**Comment by abehidek** [comment]
Thank you so much @maykbrito, it helped alot! as expected from someone who works with Rocketseat haha

**Comment by theslyprofessor** [comment]
I get error:
Error: 
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".tmp" for /local/Programming_Local/Javascript/midimaze/js/node_68e5f98e7fdd7.tmp
    at new NodeError (node:internal/errors:329:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:102:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:231:31)
    at async Loader.import (node:internal/modules/esm/loader:165:17)
    at async Object.loadESM (node:internal/process/esm_loader:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

**Comment by Miramac** [comment]
Sorry guys for the late reply...

Thanks to @yoko0180 and @maykbrito 
Is now fixed (#39)

**Comment by Artur-STN** [comment]
when I press f8 to run my code on the terminal using Node.JS Exec it creates a folder

**Comment by Artur-STN** [comment]
in this case, he created this folder:
node_fce0ea9549bc5.tmp
