### ISSUE TITLE
Problema para executar o arquivo

### ISSUE THREAD

**Issue by renatopedrosal** [Miramac/vscode-exec-node#41]
Quando pressiono F8 para executar, ele abre o terminal do VScode e da uma mensagem "Info: Start process (14:06:06)" e na barra inferior aparece "running", mas o código não é executado. Como resolver?

**Comment by mustafaneto** [comment]
Também estou com o mesmo problema

**Comment by renatopedrosal** [comment]
Consegui resolver desinstalando o node.js e instalando novamente. Caso não consiga entre em contato que tem alguns comando que funcionam também.

**Comment by luiscarlos3001** [comment]
O meu também aparece essa mensagem - Info: Start process (22:45:09), como resolver ? ( uso linux )
