### ISSUE TITLE
Environment variable setting

### ISSUE THREAD

**Issue by sunheat** [Miramac/vscode-exec-node#8]
It would be nice if default environment variables can be specified with this extension. For instance HTTP_PROXY.

**Comment by Miramac** [comment]
Sorry for the delay, I was on holiday :) 
I like the idea and will add it soon.

**Comment by Miramac** [comment]
new setting for environment variables
````json
{
  "miramac.node.env": {
      "NODE_ENV": "production"
  }
}
````
